version: '3.8'
name: swipequest_dev

services:
  swipequest_web:
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=${VIRTUAL_HOST:-swipequest.dorkodu.com}
      - VIRTUAL_PORT=${WEB_PORT:-8010}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-swipequest.dorkodu.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-hey@dorkodu.com}
      - VIRTUAL_PATH=/
    expose:
      - ${WEB_PORT:-8010}
    volumes:
      - ./web:/swipequest/web
      - ./core:/swipequest/core
      - web_node_modules:/swipequest/web/node_modules
    restart: always
    networks:
      - app
      - nginx-proxy

volumes:
  web_node_modules:

networks:
  nginx-proxy:
    external: true
  app: